theme: jekyll-theme-minimal
title: 'Coming Soon\: 24cast by BPR'
description: An innovative election prediction model created by the Brown Political Review's Data Board.
domain: 24cast.org
url: https://24cast.org
