theme: jekyll-theme-minimal
title: '24cast.org by BPR'
description: 24cast.org is currently undergoing maintenance as we upgrade our model from running 500 simulations to running 100k. Thank you for your patience.
domain: 24cast.org
url: https://24cast.org
